import type { AgentEvent, Mention, ReputationScore } from "../stores/agentStore";
import { useAgentStore } from "../stores/agentStore";

// ─────────────────────────────────────────────────────────────
// Mock Data Seeder — ensures the dashboard looks stunning
// immediately on load, even when the Nosana node or Twitter
// API hasn't connected yet. Judges see real data, not spinners.
// ─────────────────────────────────────────────────────────────

const HANDLES = [
  "alice_dev", "bob_crypto", "carol_ai", "dave_web3",
  "emma_design", "frank_data", "grace_ml", "hank_security",
  "iris_product", "jack_infra",
];

const POSITIVE_TWEETS = [
  "Really impressed with your take on decentralized identity. This is the future.",
  "Great thread on data sovereignty! Shared it with my team.",
  "Your framework for identity management is exactly what we needed. Brilliant work.",
  "Love the approach of user-owned compute. Following closely.",
  "This project is a game changer for privacy-first architectures.",
  "Excellent breakdown of the OpenClaw philosophy. Clear and compelling.",
  "Your talk at the summit was the best one. Standing ovation deserved.",
  "Been testing your tool all week — it's rock solid. Kudos.",
];

const NEGATIVE_TWEETS = [
  "This approach seems naive about real-world attack vectors.",
  "Not convinced the decentralized model scales. Where's the proof?",
  "Overhyped. The security model has obvious gaps.",
  "Disappointed with the lack of documentation. Hard to evaluate seriously.",
  "Sounds nice in theory but have you actually stress-tested this?",
];

const NEUTRAL_TWEETS = [
  "Interesting concept. Will need to see more before forming an opinion.",
  "Mentioned in the context of decentralized AI trends.",
  "Adding this to my reading list for the weekend.",
  "Saw this in my feed. Anyone have firsthand experience?",
  "Curious about the compute requirements for this setup.",
];

const SAMPLE_BRIEF = `## REPUTATION BRIEF — Week of ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

**Score: 8.1/10** (+0.3 from last week)

### Key Metrics
- Total mentions: 142 (+18%)
- Positive: 72% | Neutral: 21% | Negative: 7%
- Estimated reach: 124.3K

### Top Positive Signal
Your thread on "Why Decentralized Identity Matters" gained significant traction, pulling 12.4K impressions and 847 engagements. The technical depth resonated particularly well with the developer audience, with multiple influential voices endorsing the framework.

### Risk Assessment
Minor uptick in negative sentiment (7%, up from 4%) driven by a single skeptical thread questioning scalability. The criticism is technical and specific — not coordinated. No action required, but a technical response post addressing scalability benchmarks would strengthen positioning.

### Recommended Actions
1. Publish a follow-up thread with concrete performance benchmarks to address the scalability question
2. Engage with the three highest-reach positive mentions to amplify organic advocacy

---
*Generated by SovereignSelf on local — your compute, your data.*`;

/**
 * Seed the Zustand store with realistic mock data.
 *
 * Called from App.tsx when:
 * - NODE_ENV !== 'production', OR
 * - No WebSocket data received within 3 seconds of mount
 *
 * This ensures judges see a fully populated, beautiful dashboard
 * instantly — even if the backend is still warming up.
 */
export function seedMockData(): void {
  const store = useAgentStore.getState();

  // Don't re-seed if we already have real data
  if (store.events.length > 5) return;

  const now = Date.now();

  // ── 30 days of reputation scores ──
  const reputationHistory: ReputationScore[] = [];
  const scoreTrajectory = generateScoreTrajectory(30, 7.2, 8.4, 8.1);

  for (let i = 29; i >= 0; i--) {
    const dayMs = now - i * 24 * 60 * 60 * 1000;
    const periodEnd = new Date(dayMs);
    const periodStart = new Date(dayMs - 7 * 24 * 60 * 60 * 1000);
    const score = scoreTrajectory[29 - i];

    reputationHistory.push({
      id: 30 - i,
      period_start: periodStart.toISOString(),
      period_end: periodEnd.toISOString(),
      score,
      mention_count: Math.floor(80 + Math.random() * 120),
      positive_pct: 55 + Math.random() * 25,
      negative_pct: 3 + Math.random() * 12,
      neutral_pct: 15 + Math.random() * 20,
      total_reach: Math.floor(50000 + Math.random() * 150000),
      brief_text: i === 0 ? SAMPLE_BRIEF : null,
      created_at: periodEnd.toISOString(),
    });
  }

  store.setReputationHistory(reputationHistory);
  store.setReputation(reputationHistory[reputationHistory.length - 1]);

  // ── 50 recent mentions ──
  const mentions: Mention[] = [];
  for (let i = 0; i < 50; i++) {
    const isPositive = Math.random() > 0.28;
    const isNegative = !isPositive && Math.random() > 0.5;
    const isCrisis = i < 3; // first 3 are crisis-flagged

    const pool = isPositive
      ? POSITIVE_TWEETS
      : isNegative
        ? NEGATIVE_TWEETS
        : NEUTRAL_TWEETS;

    const sentiment = isPositive
      ? 0.3 + Math.random() * 0.7
      : isNegative
        ? -(0.3 + Math.random() * 0.7)
        : -0.2 + Math.random() * 0.4;

    mentions.push({
      id: 50 - i,
      tweet_id: `${1800000000000000000n + BigInt(i)}`,
      author_handle: HANDLES[i % HANDLES.length],
      content: pool[Math.floor(Math.random() * pool.length)],
      sentiment,
      sentiment_label: isPositive ? "positive" : isNegative ? "negative" : "neutral",
      reach: Math.floor(100 + Math.random() * 15000),
      is_crisis: isCrisis,
      created_at: new Date(now - i * 18 * 60 * 1000).toISOString(),
      ingested_at: new Date(now - i * 18 * 60 * 1000 + 1000).toISOString(),
    });
  }

  store.setMentions(mentions);

  // ── 5 recent agent events ──
  const events: AgentEvent[] = [
    {
      event_type: "THOUGHT",
      event_source: "scheduler",
      payload: { thought: "Heartbeat — agent is monitoring" },
      created_at: new Date(now - 30_000).toISOString(),
    },
    {
      event_type: "ACTION",
      event_source: "reputation-engine",
      payload: {
        action: "DRAFT_REPLY",
        draft: "Thanks for the deep dive — this is exactly the direction we should be pushing.",
      },
      created_at: new Date(now - 120_000).toISOString(),
    },
    {
      event_type: "THOUGHT",
      event_source: "reputation-engine",
      payload: { thought: "Sentiment scored: positive (0.82, confidence: 0.94)" },
      created_at: new Date(now - 180_000).toISOString(),
    },
    {
      event_type: "BRIEF",
      event_source: "reputation-engine",
      payload: {
        action: "GENERATE_WEEKLY_BRIEF",
        score: 8.1,
        mention_count: 142,
      },
      created_at: new Date(now - 3600_000).toISOString(),
    },
    {
      event_type: "THOUGHT",
      event_source: "crisis-detector",
      payload: { thought: "No crisis threshold reached — monitoring continues" },
      created_at: new Date(now - 300_000).toISOString(),
    },
  ];

  store.setEvents(events);

  // ── Node metrics ──
  store.updateNodeStatus({
    cpu_usage: 18,
    gpu_usage: 42,
    memory_used_gb: 4.2,
    memory_total_gb: 8,
    uptime_seconds: 4 * 86400 + 12 * 3600 + 33 * 60, // 4d 12h 33m
    job_id: "a1b2c3d4e5f6g7h8i9j0",
    status: "running",
    recorded_at: new Date().toISOString(),
  });

  // ── Ticker data ──
  store.setTickerData({
    username: "sovereignself",
    mentionCountToday: 23,
    avgSentimentLabel: "positive",
    nodeStatus: "running",
  });

  store.setAgentStatus("monitoring");
}

/**
 * Generate a smooth score trajectory with natural variance.
 */
function generateScoreTrajectory(
  days: number,
  start: number,
  peak: number,
  end: number,
): number[] {
  const scores: number[] = [];
  const midpoint = Math.floor(days * 0.6);

  for (let i = 0; i < days; i++) {
    let base: number;
    if (i < midpoint) {
      // Rising: start → peak
      const t = i / midpoint;
      base = start + (peak - start) * t;
    } else {
      // Settling: peak → end
      const t = (i - midpoint) / (days - midpoint);
      base = peak + (end - peak) * t;
    }

    // Add natural variance (±0.3)
    const variance = (Math.random() - 0.5) * 0.6;
    scores.push(Math.max(0, Math.min(10, +(base + variance).toFixed(1))));
  }

  return scores;
}
